### ISSUE TITLE
Homepage cards

### ISSUE THREAD

**Issue by ArkVex** [angulardevelopment/shopping-app#5]

**Comment by sunny7899** [comment]
Go ahead @ayush1009208

**Comment by ArkVex** [comment]
@sunny7899 did you merge it?

**Comment by ArkVex** [comment]
Hey @sunny7899 its not showing in prs
Did you merge it?

**Comment by sunny7899** [comment]
@ayush1009208 yes the Pr is merged. Anything left?

**Comment by ArkVex** [comment]
Why isnt it counting towards my hacktober contribution?

**Comment by ArkVex** [comment]
Its still stuck on the same

**Comment by ArkVex** [comment]
Nvm its done
thanks

**Comment by sunny7899** [comment]
@ayush1009208  can u share your hacktoberfest dashboard here?

**Comment by ArkVex** [comment]
![image](https://github.com/user-attachments/assets/2df342fa-364a-48ae-b88a-bcf8d207efa9)

**Comment by sunny7899** [comment]
@ayush1009208 No PRs status what its showing
